version: "3.9"

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  brightness_service:
    container_name: brightness
    depends_on:
      - mongo
    build:
      context: brightnessService
      dockerfile: Dockerfile
    ports:
      - 8893:8893

  temperature_service:
    container_name: temperature
    depends_on:
      - mongo
    build:
      context: temperatureService
      dockerfile: Dockerfile
    ports:
      - 8895:8895

  humidity_service:
    container_name: humidity
    depends_on:
      - mongo
    build:
      context: humidityService
      dockerfile: Dockerfile
    ports:
      - 8891:8891

  soil_moisture_service:
    container_name: soil_moisture
    depends_on:
      - mongo
    build:
      context: soilMoistureService
      dockerfile: Dockerfile
    ports:
      - 8894:8894

  operation_service:
    container_name: operation
    depends_on:
      - mongo
      - greenhouse_communication_gateway
    build:
      context: operationService
      dockerfile: Dockerfile
    ports:
      - 8896:8896

  client_communication_gateway:
    container_name: client_communication
    depends_on:
      - greenhouse_service
      - temperature_service
      - brightness_service
      - soil_moisture_service
      - humidity_service
      - operation_service
    build:
      context: clientCommunicationGateway
      dockerfile: Dockerfile
    ports:
      - 8890:8890
      - 1234:1234
      - 1235:1235

  greenhouse_communication_gateway:
    container_name: greenhouse_communication
    depends_on:
      - greenhouse_service
    build:
      context: greenhouseCommunicationGateway
      dockerfile: Dockerfile
    ports:
      - 8892:8892
      - 1883:1883

  greenhouse_service:
    container_name: greenhouse #name that must be used as host in http request between containers
    depends_on:
      - mongo
      - temperature_service
      - brightness_service
      - soil_moisture_service
      - humidity_service
      - operation_service
      - client_communication_gateway
    build:
      context: greenhouseService
      dockerfile: Dockerfile
    ports:
      - 8889:8889

